title: Appstew
author: appstew
email: damilee2734@gmail.com
description: >-
  Appstew.github.io

social:
  twitter: appstew
  facebook: appstew
  instagram: appstew
  github: appstew
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
